###Create Match
POST http://localhost:3000/match/create
Content-Type: application/json

{
    "opponent": "Velez"
}


### End a match
PATCH http://localhost:3000/match/end/1
Content-Type: application/json

{
    "finalScore": 30,
    "opponentFinalScore": 29
}