
### Create an user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "probando2@gmail.com",
    "password": "123456",
    "name": "Nombre",
    "surname": "Apellido"
}

### Log in with an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "probando2@gmail.com",
    "password": "123456"
}

### Get the current logged in user
GET http://localhost:3000/auth/me

### Signout user
POST http://localhost:3000/auth/signout
Content-Type: application/json

{
  
}

### Make an admin
PATCH http://localhost:3000/auth/make-admin
Content-Type: application/json

{
    "id": 1
}

### remove an admin
PATCH http://localhost:3000/auth/remove-admin
Content-Type: application/json

{
     "id": 1
}